package com.wadpam.product.dao;

/**
 * Implementation of Business Methods related to entity Di18n.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-01-13T12:47:25.947+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class Di18nDaoBean 
	extends GeneratedDi18nDaoImpl
		implements Di18nDao 
{

	// TODO: implement your Business Methods here

}
