package com.wadpam.product.dao;

/**
 * Business Methods interface for entity DpCategory.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-01-13T12:47:25.947+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DpCategoryDao extends GeneratedDpCategoryDao {

	// TODO: declare your Business Methods here
	
}
